import headerMovement from "./headerMovement.js";
import scrollNavigation from "./scrollNavigation.js";
import animations from "./animations.js";
import productsSlider from "./productsSlider.js";
import mobileNavigation from "./mobileNavigation.js";
import '../public/styles/main.css';
productsSlider();
headerMovement();
mobileNavigation();
scrollNavigation();
animations();